---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
 

## 網站資料爬取
```{r}
library(xml2)
library(rvest) 
frame = data.frame(Title=character(),
                      Author=character(),
                      PushNum=character())
for(i in 5294:5299){
PTTURL<-paste0("https://www.ptt.cc/bbs/movie/index",i,".html") 
PTTContent <- read_html(PTTURL)
post_title <- PTTContent %>% html_nodes(".title") %>% html_text() 
post_title <- gsub("\n",replacement="",post_title)
post_title <- gsub("\t",replacement="",post_title)
post_author<- PTTContent %>% html_nodes(".author") %>% html_text()
post_pushnum <- PTTContent %>% html_nodes(".nrec") %>% html_text()
PTTframe <- data.frame(Title = post_title, Author = post_author, PushNum = post_pushnum)
frame <- rbind(frame,PTTframe)
}

```



## 爬蟲結果呈現
```{r}
knitr::kable(frame)
```

## 解釋爬蟲結果 
```{r}
str(frame)
#共爬出115個電影標題
table(frame$Author)
#如下所示：「-」作者為最多貼文數，不過在ppt中，作者名稱被標示為「-」，都是被管理員所刪除的貼文，故不予計算，最多貼文的作者應為「jay5566」。

```

1.共爬出115個電影標題


2.如下所示：「-」作者為最多貼文數，不過在ppt中，作者名稱被標示為「-」，都是被管理員所刪除的貼文，故不予計算，最多貼文的作者應為「jay5566」。


```{r}
#在這次爬蟲中，就標題來看發覺，鄉民們取的標題，有如新聞媒體般，充斥著誇飾、搞笑、一刀見血，對不常使用的我覺得很新鮮、有趣，和許多佛心的贈票資訊，與電影內容，讓我確實地發現這就是ptt歷久不衰的原因，因為充滿著熱心的鄉民。


```
在這次爬蟲中，就標題來看發覺，鄉民們取的標題，有如新聞媒體般，充斥著誇飾、搞笑、一刀見血，對不常使用的我覺得很新鮮、有趣，和許多佛心的贈票資訊，與電影內容，讓我確實地發現這就是ptt歷久不衰的原因，因為充滿著熱心的鄉民。
